Update authorization protocol
Issue: #6

See https://developers.strava.com/docs/getting-started/#account

diff --git a/stravaup b/stravaup
--- a/stravaup
+++ b/stravaup
@@ -63,7 +63,7 @@ if [ "$STRAVAUP_CODE" = "" ]; then
     echo "Please open the following URL in a browser"
     echo -n "https://www.strava.com/oauth/authorize?client_id="
     echo -n "$STRAVAUP_CLIENT_ID"
-    echo "&response_type=code&redirect_uri=http://localhost/index.php&approval_prompt=force&scope=write"
+    echo "&response_type=code&redirect_uri=http://localhost/index.php&approval_prompt=force&scope=activity:write"
     echo "Select 'Authorize' which will lead to a redirect into a localhost address. Copy the authorization"
     echo "code into .stravauprc"
     echo "  STRAVAUP_CODE = [insert your own]"
@@ -71,8 +71,19 @@ if [ "$STRAVAUP_CODE" = "" ]; then
 fi
 
 # Get auth token
+# If needed, get refresh token
+if [ "$STRAVAUP_REFRESH_TOKEN" = "" ]; then
+    echo "Exchanging authorization token for refresh token..."
+    STRAVAUP_REFRESH_TOKEN=$(curl -s -X POST https://www.strava.com/oauth/token -F client_id="$STRAVAUP_CLIENT_ID" -F client_secret="$STRAVAUP_CLIENT_SECRET" -F code="$STRAVAUP_CODE" -F grant_type=authorization_code | cut -d':' -f5 | cut -d',' -f1 | sed -e 's/[^a-z0-9]//g')
+    echo "STRAVAUP_REFRESH_TOKEN=$STRAVAUP_REFRESH_TOKEN" >> ${HOME}/.stravauprc
+fi
+
+echo "Getting auth token..."
+TOKEN=$(curl -s -X POST https://www.strava.com/oauth/token -F client_id="$STRAVAUP_CLIENT_ID" -F client_secret="$STRAVAUP_CLIENT_SECRET" -F grant_type=refresh_token -F refresh_token="$STRAVAUP_REFRESH_TOKEN" | grep access_token | cut -d':' -f3 | cut -d',' -f1 | sed -e 's/[^a-z0-9]//g')
+
 if [ "$TOKEN" = "" ]; then
-    TOKEN=$(curl -s -X POST https://www.strava.com/oauth/token -F client_id="$STRAVAUP_CLIENT_ID" -F client_secret="$STRAVAUP_CLIENT_SECRET" -F code="$STRAVAUP_CODE" | grep -Po '"access_token":.*?[^\\]",' | cut -d':' -f2 | sed -e 's/[^a-z0-9]//g')
+    echo "Unable to get auth token. Consider deleting STRAVAUP_REFRESH_TOKEN." 1>&2
+    exit 1
 fi
 
 # Upload file
